### ISSUE TITLE
Confusion with LexikFormFilterBundle usage

### ISSUE THREAD

**Issue by Mecanik** [PUGX/PUGXAutoCompleterBundle#75]
Hello,

A bit of a noob question (but since I'm quite new to Symfony, forgive me). I`m trying to create an auto-complete select box for a project where users can search addresses.

I have followed the documentation up until [here](https://github.com/PUGX/PUGXAutoCompleterBundle/blob/master/docs/index.md#43-filter), however I`m a bit confused of the usage.

My understanding was and is that if I use LexikFormFilterBundle with your library it would search from the entity/database without the need to have a separate controller. However, I can see that the library still tries to perform GET requests to a controller.

Is this the desired result and I am missing something? Please advise.

Thank you!

**Comment by garak** [comment]
This library is using two additional controller actions: one to search for values, and another one to display the currently selected value (if there's one).
If you want to just use it like a select2 with existing values, these actions are actually not needed, since all values are already present. Notice that this is not advisable if you estimate to have a long list of values.
